---
models:
  hmax_old:
    type: 'hmax'
    ckpt_path: '/users/jamullik/scratch/TVSD-real/models/checkpoints/ip_18_hmax_old_gpu_1_cl_0.5_ip_3_224_224_0000_c1[_6,3,1_]_bypass_1/model_best.pth.tar'
    input_size: [224, 224]
    input_channels: 3
    layers: 
      - 'model_pre.c1'
      - 'model_pre.s2b_before_2'
      - 'model_pre.s2b'

